on:
  push:
    branches:
    - main
    - release/*
    on:
  pull_request:
    branches:
    - main
    on:
#  schedule:
#  - cron: "0 2 * * 1-5"
  page_build:
  commit_comment:
    name: deploy to staging
    runs-on: ubuntu-18.04
# ubuntu-latest, ubuntu-18.04, or ubuntu-16.04 windows-latest or windows-2019 macos-latest or macos-10.15
    ECHO: |
      sudo apt-get install gnupg1 apt-transport-https dirmngr
      export INSTALL_KEY=379CE192D401AB61
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $INSTALL_KEY
      echo "deb https://ookla.bintray.com/debian generic main" | sudo tee  /etc/apt/sources.list.d/speedtest.list
      sudo apt-get update
      sudo apt-get install speedtest
# Other non-official binaries will conflict with Speedtest CLI
# Example how to remove using apt-get
# sudo apt-get remove speedtest-cli
     

Fin: "Stop"
